usr/bin
usr/share/doc
usr/share/man
etc/tor

contrib/client-tools/torify usr/bin
debian/tor-instance-create usr/sbin
debian/tor-service-defaults-torrc usr/share/tor
debian/tor-service-defaults-torrc-instances usr/share/tor
debian/systemd/tor.service usr/lib/systemd/system
debian/systemd/tor@.service usr/lib/systemd/system
debian/systemd/tor@default.service usr/lib/systemd/system
debian/systemd/tor-generator usr/lib/systemd/system-generators
